version: '3.7'

services:

  redis:
     image: redis/redis-stack:latest
     ports: 
       - 6379:6379
       - 8001:8001

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025 # Web ui port
      - 1025:1025 # mail server port

  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   ports:
  #     - "5672:5672" # Message port
  #     - "15672:15672" # Web UI
  #   volumes:
  #     - 'rabbitmq_data:/data'

  eventstore:
    image: eventstore/eventstore:23.10.0-bookworm-slim
    ports:
      - '2113:2113'
      - '1112:1112'
      - '1113:1113'
    environment:
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      PROJECTION_THREADS: 8
      INSECURE: true
      EVENTSTORE_INSECURE: true
      EVENTSTORE_ENABLE_EXTERNAL_TCP: true
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: true

    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
      
  es-labs-messagehub:
    image: es-labs-messagehub:latest
    build:
      context: .
      dockerfile: ./es-labs-messagehub.Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+;http://+" 
      ASPNETCORE_HTTPS_PORT: 4081 # -e ASPNETCORE_HTTPS_PORT=4081
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/es-labs-messagehub.pfx # -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "p455w0rd" # -e ASPNETCORE_Kestrel__Certificates__Default__Password="<CREDENTIAL_PLACEHOLDER>"
    depends_on:
      - eventstore
    ports:
      - '4000:80'
      - '4001:443'
    volumes:
      - $CERTS_FOLDER:/https/ # -v ${HOME}/.aspnet/https:/https/

# docker run --rm -it -e ASPNETCORE_Kestrel__Certificates__Default__Password="<CREDENTIAL_PLACEHOLDER>" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx mcr.microsoft.com/dotnet/samples:aspnetapp

  cqrs1:
    image: cqrs1:latest
    # build:
    #   context: .
    #   dockerfile: ../miss-leanskin/src/Dockerfile.CommandQueryApi
    #   tags:
    #     - latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      #ASPNETCORE_URLS: http://+:8080
      # eventstore
      ConnectionStrings__REDIS: redis:6379
      ConnectionStrings__EventStore: esdb://admin:changeit@eventstore:2113?tls=false&tlsVerifyCert=false
    depends_on:
      - eventstore
    ports:
      - '8090:8080'
      - '8080:8080'
      - '8091:8081'
      
  esapi:
    image: esapi:latest
    build:
      context: .
      dockerfile: ./ESApi.Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+;http://+"
      #ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_HTTPS_PORT: 6081
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/es-labs-messagehub.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "p455w0rd"
      # eventstore
      ConnectionStrings__REDIS: redis:6379
      ConnectionStrings__EventStore: esdb://admin:changeit@eventstore:2113?tls=false&tlsVerifyCert=false
    depends_on:
      - eventstore
      - es-labs-messagehub
    ports:
      - '6000:80'
      - '6001:443'
      # - '8060:8080'
      # - '8061:6001'
    volumes:
      - $CERTS_FOLDER:/https/

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:



#   docker pull mcr.microsoft.com/dotnet/samples:aspnetapp
# docker run --rm -it -p 8000:80 -p 8001:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="<CREDENTIAL_PLACEHOLDER>" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v ${HOME}/.aspnet/https:/https/ mcr.microsoft.com/dotnet/samples:aspnetapp