
@TurnstileLocationStore = 1

#@TurnstileLocationZone = 0A
@TurnstileLocationZone = A0

@Date = 2024-01-19

###

POST http://localhost:4000/events/TurnstilePassageDetected
# Accept: application/json
Content-Type: application/json

{
  "__timestamp": "{{Date}}",
  "direction": "Clockwise",
  "__direction": "CounterClockwise",
  "turnstile": {
    "__store": "{{TurnstileLocationStore}}",
    "SerialNumber": "{{TurnstileLocationStore}}-{{TurnstileLocationZone}}"
  }
}


### Enter

POST http://localhost:4000/events/TurnstilePassageDetected
Content-Type: application/json

{
  "direction": "Clockwise",
  "turnstile": {
    "SerialNumber": "{{TurnstileLocationStore}}-0A"
  }
}

### Exit

POST http://localhost:4000/events/TurnstilePassageDetected
Content-Type: application/json

{
  "direction": "Clockwise",
  "turnstile": {
    "SerialNumber": "{{TurnstileLocationStore}}-A0"
  }
}

###

GET http://localhost:4000/queries/stores/{{Date}}
Accept: application/json

###

GET http://localhost:4000/queries/store-{{TurnstileLocationStore}}/{{Date}}
Accept: application/json







### Manually set zone  

POST http://localhost:4000/commands/AdjustZone
Content-Type: application/json

{
  "__timestamp": "{{Date}}",
  "store": "{{TurnstileLocationStore}}",
  "zone": "D",
  "who": "some admin",
  "reason": "some reason",
  "NumberOfVisitors": 10
}






















###

POST http://localhost:4000/events/TurnstilePassageDetected
# Accept: application/json
Content-Type: application/json

{
  "timestamp": "{{Date}}",
  "direction": "Clockwise",
  "__direction": "CounterClockwise",
  "turnstile": {
    "__store": "{{TurnstileLocationStore}}",
    "SerialNumber": "{{TurnstileLocationStore}}-{{TurnstileLocationZone}}"
  }
}