
name: Main Branch Workflow

on:
    push:
        branches:
            - main
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build project
              run: |
                    # Add build commands here
            - name: Run tests
              run: |
                    # Add test commands here
                    
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                        Changes in this Release:
                        - Add feature A
                        - Fix bug B
                  draft: false
                  prerelease: false
